LineLength:
  Enabled: false

MethodLength:
  Max: 30

SymbolName:
  AllowCamelCase: false

Documentation:
  Enabled: false

AllCops:
  Includes:
    - Rakefile
    - Gemfile
    - config.ru
  Excludes:
    - lib/public/**
    - build/**
